api/urls.py
from rest_framework.routers import DefaultRouter
from api.viewsets import core_viewsets
from django.urls import path, include
from api.viewsets import core_viewsets
from api.viewsets import front_viewset

router = DefaultRouter()
router.register(r'slider', core_viewsets.SliderViewSet)
router.register(r'identify_open_space', core_viewsets.CreateOpenSpaceViewSet)
router.register(r'resource', core_viewsets.ResourceViewSet)
router.register(r'province', core_viewsets.ProvinceViewSet)
router.register(r'district', core_viewsets.DistrictViewSet)
router.register(r'municipality', core_viewsets.MunicipalityViewSet)

router.register(r'suggested_use', core_viewsets.SuggestedUseViewSet)
router.register(r'service', core_viewsets.ServiceViewSet)
router.register(r'service_list', core_viewsets.ServiceListViewSet)
# router.register(r'question', core_viewsets.QuestionViewSet)
router.register(r'open_space', core_viewsets.OpenSpaceViewSet)
router.register(r'report', core_viewsets.ReportViewSet)

router.register(r'header', front_viewset.HeaderViewSet)
router.register(r'open_space_ide', front_viewset.OpenSpaceIdeViewSet)
router.register(r'open_space_def', front_viewset.OpenSpaceDefViewSet)

router.register(r'contact', front_viewset.ContactViewSet)
router.register(r'open_space_app', front_viewset.OpenSpaceAppViewSet)
router.register(r'gallery', core_viewsets.GalleryViewSet)
router.register(r'message', front_viewset.MessageViewSet)

# about page urls

router.register(r'about_header', front_viewset.AboutHeaderViewSet)
router.register(r'about_criteria_description', front_viewset.CriteriaDescriptionViewSet)
router.register(r'about_criteria_type', front_viewset.CriteriaTypeViewSet)
router.register(r'about_why_map_open_space', front_viewset.WhyMapOpenSpaceViewSet)
router.register(r'about_why_map_open_icon', front_viewset.WhyMapOpenIconViewSet)
router.register(r'about_open_space_criteria', front_viewset.OpenSpaceCriteriaViewSet)




urlpatterns = [
    path('', include(router.urls)),
    path('glimpse_of_open_space', core_viewsets.GlimpseOfOpenSpace.as_view()),
    path('open_space_landing', core_viewsets.OpenSpaceLandingApi.as_view()),
    path('district_api', core_viewsets.DistrictApi.as_view()),
    path('municipality_api', core_viewsets.MunicipalityApi.as_view()),
    path('province_api', core_viewsets.ProvinceApi.as_view()),
    path('open_space_geo_json',
         core_viewsets.OpenSpaceGeojsonViewSet.as_view()),
    path('single_open_geo_json',
         core_viewsets.SingleOpenSpaceGeojsonViewSet.as_view()),
    path('district_geo_json',
         core_viewsets.DistrictGeojsonViewSet.as_view()),
    path('municipality_geo_json',
         core_viewsets.MunicipalityGeojsonViewSet.as_view()),
    path('province_geo_json',
         core_viewsets.ProvinceGeojsonViewSet.as_view()),
    path('near_by_me', core_viewsets.NearByMeViewSet.as_view()),
    path('alternative_near_by_me', core_viewsets.AlternativeNearByMeViewSet.as_view()),
    path('open_extra', core_viewsets.AddedOpenAPi.as_view()),
    path('open_post_location', core_viewsets.OpenSpaceNearBy.as_view()),
    path('identify_open_space_new', core_viewsets.CreateNewOpenSpaceViewSet.as_view()),
    path('about_criteria_type_description', front_viewset.AboutCriteriaTypeViewSet.as_view()),
    # path('distance', core_viewsets.DistanceApi.as_view()),
    path('near_by_openspace', core_viewsets.NearByMeOpenSpace.as_view()),
    path('unique_municipality', front_viewset.UniqueMunicipalityOfMessage.as_view()),
    path('district-tile/<int:zoom>/<int:x>/<int:y>', core_viewsets.district_tile),
    path('municipality-tile/<int:zoom>/<int:x>/<int:y>', core_viewsets.municipality_tile),
    path('province-tile/<int:zoom>/<int:x>/<int:y>', core_viewsets.municipality_tile),

]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views

urlpatterns = [
    path('home/', views.HomePage.as_view(), name='home'),
    path('create-user/', views.CreateUser, name='create-user'),
    path('reply-report/', views.report_reply, name='reply-report'),
    path('user-list/', views.UserList.as_view(), name='user-list'),
    path('activate/<int:id>', views.activate_user, name='activate'),
    path('delete/<str:model>/<int:id>/<str:url>', views.deleteData, name='delete'),
    path('delete_front/<str:model>/<int:id>/<str:url>', views.deleteDataFront, name='delete'),
    path('delete_dashboard/<str:model>/<int:id>/<str:url>', views.deleteDataDashboard, name='delete_dashboard'),

    path('upload-shapefile/', views.importShapefile, name='upload-shapefile'),
    path('openspace-list/<str:hlcit_code>', views.OpenSpaceList.as_view(), name='openspace-list'),
    path('community-space-list/<str:hlcit_code>', views.CommunitySpaceList.as_view(), name='community_space_list'),
    path('add-community-space-options/<str:hlcit_code>', views.AddCommunitySpaceOptions.as_view(),
         name='add_community_space_options'),
    path('openspace-add/<str:hlcit_code>', views.OpenSpaceCreate.as_view(), name='openspace-add'),
    path('openspace-edit/<int:pk>', views.OpenSpaceUpdate.as_view(), name='openspace-edit'),
    path('community-space-add/<str:hlcit_code>', views.CommunitySpaceCreate.as_view(), name='community_space_add'),
    path('community-space-edit/<int:pk>', views.CommunitySpaceUpdate.as_view(), name='community_space_update'),

    path('available-list/', views.AvailableFacilityList.as_view(), name='available-list'),
    path('available-add/', views.AvailableFacilityCreate.as_view(), name='available-add'),

    path('report-list/', views.ReportList.as_view(), name='report-list'),

    path('gallery-list/<int:id>', views.GalleryLists.as_view(), name='gallery-list'),
    path('gallery-add/<int:id>', views.GalleryCreate.as_view(), name='gallery-add'),
    path('gallery-edit/<int:pk>/<int:id>', views.GalleryUpdate.as_view(), name='gallery-edit'),

    path('question-list/', views.QuestionsList.as_view(), name='question-list'),
    path('question-add/', views.QuestionCreate.as_view(), name='question-add'),
    path('question-edit/<int:pk>', views.QuestionUpdate.as_view(), name='question-edit'),

    path('questiondata-list/<int:id>', views.QuestionData.as_view(), name='questiondata-list'),
    path('questiondata-add/<int:id>', views.QuestionDataCreate.as_view(), name='questiondata-add'),
    path('questiondata-edit/<int:pk>/<int:id>', views.QuestionDataUpdate.as_view(), name='questiondata-edit'),

    path('suggest-list/', views.SuggestedUseLists.as_view(), name='suggest-list'),
    path('suggest-add/', views.SuggestedCreate.as_view(), name='suggest-add'),
    path('suggest-edit/<int:pk>', views.SuggestedUpdate.as_view(), name='suggest-edit'),

    path('suggestdata-list/<int:id>', views.SuggestedUseDataList.as_view(), name='suggestdata-list'),
    path('suggestdata-add/<int:id>', views.SuggestedDataCreate.as_view(), name='suggestdata-add'),
    path('suggestdata-edit/<int:pk>/<int:id>', views.SuggestedDataUpdate.as_view(), name='suggestdata-edit'),

    path('service-list/', views.ServiceLists.as_view(), name='service-list'),
    path('service-add/', views.ServiceCreate.as_view(), name='service-add'),
    path('service-edit/<int:pk>', views.ServiceUpdate.as_view(), name='service-edit'),

    path('servicedata-list/<int:id>', views.ServiceDataList.as_view(), name='servicedata-list'),
    path('servicedata-add/<int:id>', views.ServiceDataCreate.as_view(), name='servicedata-add'),
    path('servicedata-edit/<int:pk>/<int:id>', views.ServiceDataUpdate.as_view(), name='servicedata-edit'),

    path('resource-list/', views.ResourceList.as_view(), name='resource-list'),
    path('resource-add/', views.ResourceCreate.as_view(), name='resource-add'),
    path('resource-edit/<int:pk>', views.ResourceUpdate.as_view(), name='resource-edit'),

    path('resource-category-list/', views.ResourceCategoryList.as_view(), name='resource-category-list'),
    path('resource-category-add/', views.ResourceCategoryCreate.as_view(), name='resource-category-add'),
    path('resource-category-edit/<int:pk>', views.ResourceCategoryUpdate.as_view(), name='resource-category-edit'),

    path('resource-document-list/', views.ResourceDocumentList.as_view(), name='resource-document-list'),
    path('resource-document-add/', views.ResourceDocumentTypeCreate.as_view(), name='resource-document-add'),
    path('resource-document-edit/<int:pk>', views.ResourceDocumentTypeUpdate.as_view(), name='resource-document-edit'),

    path('header-list/', views.HeaderList.as_view(), name='header-list'),
    path('header-update/<int:pk>', views.HeaderUpdate.as_view(), name='header-update'),
    path('slider-list/', views.SliderList.as_view(), name='slider-list'),
    path('slider-update/<int:pk>', views.SliderUpdate.as_view(), name='slider-update'),
    path('slider-add/', views.SliderCreate.as_view(), name='slider-create'),

    path('openspace-definition-list/', views.OpenSpaceDefinitionList.as_view(), name='openspace-definition-list'),
    path('openspace-definition-update/<int:pk>', views.OpenSpaceDefinitionUpdate.as_view(),
         name='openspace-definition-update'),

    path('openspace-identification-list/', views.OpenSpaceIdentificationList.as_view(),
         name='openspace-identification-list'),
    path('openspace-identification-update/<int:pk>', views.OpenSpaceIdentificationUpdate.as_view(),
         name='openspace-identification-update'),

    path('openspace-identification-process-list/', views.OpenSpaceIdentificationProcessList.as_view(),
         name='openspace-identification-process-list'),
    path('openspace-identification-process-update/<int:pk>', views.OpenSpaceIdentificationProcessUpdate.as_view(),
         name='openspace-identification-process-update'),
    path('openspace-identification-process-create/', views.OpenSpaceIdentificationProcessCreate.as_view(),
         name='openspace-identification-process-create'),

    path('footer-list/', views.FooterList.as_view(), name='footer-list'),
    path('footer-update/<int:pk>', views.FooterUpdate.as_view(), name='footer-update'),

    path('app-list/', views.AppList.as_view(), name='app-list'),
    path('app-add/', views.AppCreate.as_view(), name='app-add'),
    path('app-update/<int:pk>', views.AppUpdate.as_view(), name='app-update'),

    #home page list view
    path('home_page_list/', views.homePageListView, name='app-update'),

    path('open_new_list/', views.OpenSpaceMuniList.as_view(), name='open_muni'),

    path('amenity-type/<str:hlcit_code>', views.MunicipalityAmenityTypeList.as_view(),
         name='municipality_amenity_type'),
    path('amenity_type/', views.AmenityTypeList.as_view(),
         name='amenity_type'),

    path('municipality-available-amenities-list/<str:title>/<str:hlcit_code>',
         views.MunicipalityAvailableAmenityFacilityList.as_view(), name='municipality_available_ameni_list'),
    path('available_ameni_list/<str:title>/', views.AvailableAmenityFacilityList.as_view(),
         name='available_ameni_list'),
    path('amenity_type_add/', views.AvailableAmenityCreate.as_view(), name='amenity_type_add'),
    path('amenity_type_update/<int:pk>', views.AvailableAmenityUpdate.as_view(), name='amenity_type_update'),
    path('add-municipality-available-amenities/<str:hlcit_code>', views.AddBulkMunicipalityAvailableAmenities.as_view(),
         name='add_municipality_amenities'),

    path('create_agency/', views.create_agency, name='create_agency'),
    path('activate_agency/<int:id>/', views.activate_agency, name='activate_agency'),
    path('agency_list/', views.AgencyList.as_view(), name='agency_list'),

    path('agency_message/', views.AgencyMessageList.as_view(), name='agency_message'),
    path('agency_message_add/', views.AgencyMessageCreate.as_view(), name='agency_message_add'),
    path('agency_message_update/<int:pk>', views.AgencyMessageUpdate.as_view(), name='agency_message_update'),
    path('publish_report/<int:pk>', views.publish_report, name='publish_report'),

    path('about_page', views.aboutPageListView, name='about_page'),
    path('why_map_open_space_list', views.WhyMapOpenSpaceList.as_view(), name='why-openspace-list'),
    path('why_map_open_space_update/<int:pk>', views.WhyMapOpenSpaceUpdate.as_view(), name='why-openspace-list'),

    path('why_map_open_icon_list', views.WhyMapOpenSpaceIconList.as_view(), name='why-openicon-list'),
    path('why_map_open_icon_update/<int:pk>', views.WhyMapOpenSpaceIconUpdate.as_view(), name='why-openspace-update'),
    path('why_map_open_icon_add/', views.WhyMapOpenSpaceIconCreate.as_view(), name='why-openspace-add'),


    path('about_header_list/', views.AboutHeaderList.as_view(), name='about-header-list'),
    path('about_header_update/<int:pk>', views.AboutHeaderUpdate.as_view(), name='about-header-update'),

    path('open_criteria_list/', views.OpenSpaceCriteriaList.as_view(), name='openspace-criteria-list'),
    path('open_criteria_update/<int:pk>', views.OpenSpaceCriteriaUpdate.as_view(), name='openspace-criteria-update'),


    path('about_criteria_type_list/', views.AboutCriteriaTypeList.as_view(), name='about-criteria-type-list'),
    path('about_criteria_type_add/', views.AboutCriteriaTypeCreate.as_view(), name='about-criteria-type-add'),
    path('about_criteria_type_update/<int:pk>', views.AboutCriteriaTypeUpdate.as_view(), name='about-criteria-type-update'),


    path('about_criteria_type_description_list/<str:criteria_type>', views.AboutCriteriaTypeDescriptionList.as_view(), name='about-criteria-type-des-list'),
    path('about_criteria_type_description_add/<str:criteria_type>', views.AboutCriteriaTypeDescriptionCreate.as_view(), name='about-criteria-type-description-add'),

iom/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('api/v2/', include('api.v2_urls')),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#
#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),
#
#     ] + urlpatterns

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from core.models import Province, District, Municipality, OpenSpace


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    name = models.CharField(max_length=300, null=True, blank=True)
    email = models.CharField(max_length=300, null=True, blank=True)
    # Province = models.ForeignKey(Province, on_delete=models.CASCADE, related_name='Province', null=True, blank=True)
    # District = models.ForeignKey(District, on_delete=models.CASCADE, related_name='District', null=True, blank=True)
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE, related_name='Municipality', null=True,
                                     blank=True)
    image = models.ImageField(upload_to='upload/profile/', null=True, blank=True)

    def __str__(self):
        return self.name


class UserAgency(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='agency')
    agency_name = models.CharField(max_length=300, null=True, blank=True)
    email = models.CharField(max_length=300, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    contact = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.agency_name


class AgencyMessage(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    agency = models.ForeignKey(UserAgency, on_delete=models.CASCADE)
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE, related_name='user_agency')
    open_space = models.ForeignKey(OpenSpace, on_delete=models.CASCADE, related_name='user_agency')
    message = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.agency.agency_name

dashboard/templates/about_criteria_type_description_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Main Content -->

<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Open Space Definition form</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/"><i class="la la-home"></i> IOM</a></li>
                    <li class="breadcrumb-item">Pagewise content </li>
                    <li class="breadcrumb-item ">About Page</li>
                    <li class="breadcrumb-item ">Open Space Selection Criteria Features Types</li>
                    <li class="breadcrumb-item ">Manage Feature Description</li>
                    <li class="breadcrumb-item active">update form</li>
                </ul>
                <button class="btn btn-icon mobile_menu" type="button"><i class="la la-navicon"></i></button>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn float-right right_icon_toggle_btn" type="button"><i class="la la-arrow-right"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="project-form">

        <div class="card">
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ field.name|title }} {{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}

<!--                    {{form.as_p}}-->

                    <div class="form-group" style="display:none">
                        <label for="id_type">Type </label>
                        <div class="select-option">
                            <select class="custom-select show-tick ms select2" name="type" required id="id_type">

                                <option value="{{form.instance.type.id}}" selected>{{form.instance.type}}</option>
<!--                                {% for type in types %}-->
<!--                                <option value="{{ type.id }}">{{type.title}}</option>-->
<!--                                {% endfor %}-->
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <p><label for="id_description">Description:</label> <textarea class="form-control" name="description" cols="40" rows="10" id="id_description">{{ form.instance.description }}</textarea></p>
                      <p><label for="id_description_nep">Description nep:</label> <textarea class="form-control" name="description_nep" cols="40" rows="10" id="id_description_nep">{{ form.instance.description_nep }}</textarea></p>
                    </div>




                    <div class="form-footer pull-right">
                        <button type="submit" class="btn" role="button">Save</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock %}

dashboard/templates/footer_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Main Content -->

<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Contact form</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/"><i class="la la-home"></i> IOM</a></li>
                    <li class="breadcrumb-item active">Update form</li>
                </ul>
                <button class="btn btn-icon mobile_menu" type="button"><i class="la la-navicon"></i></button>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn float-right right_icon_toggle_btn" type="button"><i class="la la-arrow-right"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="project-form">

        <div class="card">
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ field.name|title }} {{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <div class="form-group">
                      <p><label for="id_title">Title:</label> <input class="form-control" type="text" name="title" value="{{ form.instance.title }}" maxlength="300" required id="id_title"></p>
                      <p><label for="id_location">Location:</label> <input class="form-control" type="text" name="location" value="{{ form.instance.location }}" maxlength="300" id="id_location"></p>
                      <p><label for="id_location_nep">Location nep:</label> <input class="form-control" type="text" name="location_nep" value="{{ form.instance.location_nep }}" maxlength="300" id="id_location_nep"></p>
                      <p><label for="id_num1">Num1:</label> <input class="form-control" type="text" name="num1" value="{{ form.instance.num1 }}" maxlength="14" id="id_num1"></p>
                      <p><label for="id_num1_nep">Num1 nep:</label> <input class="form-control" type="text" value="{{ form.instance.num1_nep }}" name="num1_nep" maxlength="14" id="id_num1_nep"></p>
                      <p><label for="id_num2">Num2:</label> <input class="form-control" type="text"  name="num2" value="{{ form.instance.num2 }}" maxlength="14" id="id_num2"></p>
                      <p><label for="id_num2_nep">Num2 nep:</label> <input class="form-control" type="text" name="num2_nep" value="{{ form.instance.num2_nep }}" maxlength="14" id="id_num2_nep"></p>
                      <p><label for="id_email">Email:</label> <input class="form-control" type="email" name="email" value="{{ form.instance.email }}" maxlength="254" id="id_email"></p>
                      <p><label for="id_email_nep">Email nep:</label> <input class="form-control" type="email" name="email_nep" value="{{ form.instance.email_nep }}" maxlength="254" id="id_email_nep"></p>
                      <p><label for="id_description">Description:</label> <textarea class="form-control" name="description" cols="40" rows="10" id="id_description">{{ form.instance.description }}</textarea></p>
                      <p><label for="id_description_nep">Description nep:</label> <textarea class="form-control" name="description_nep" cols="40" rows="10" id="id_description_nep">{{ form.instance.description_nep }}</textarea></p>
                    </div>






                    <div class="form-footer pull-right">
                        <button type="submit" class="btn" role="button">Save</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock %}

dashboard/templates/openspace_identification_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Main Content -->

<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Open Space Identification form</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/"><i class="la la-home"></i> IOM</a></li>
                    <li class="breadcrumb-item active">Update form</li>
                </ul>
                <button class="btn btn-icon mobile_menu" type="button"><i class="la la-navicon"></i></button>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn float-right right_icon_toggle_btn" type="button"><i class="la la-arrow-right"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="project-form">

        <div class="card">
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ field.name|title }} {{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <div class="form-group">
                      <p><label for="id_title">Title:</label> <textarea class="form-control" name="title" cols="40" rows="10" id="id_title">{{ form.instance.title }}</textarea></p>
                      <p><label for="id_title_nep">Title nep:</label> <textarea class="form-control" name="title_nep" cols="40" rows="10" id="id_title_nep">{{ form.instance.title_nep }}</textarea></p>
                      <p><label for="id_description">Description:</label> <textarea class="form-control" name="description" cols="40" rows="10" id="id_description">{{ form.instance.description }}</textarea></p>
                      <p><label for="id_description_nep">Description nep:</label> <textarea class="form-control" name="description_nep" cols="40" rows="10" id="id_description_nep">{{ form.instance.description_nep }}</textarea></p>
                    </div>


                    <div class="form-footer pull-right">
                        <button type="submit" class="btn" role="button">Save</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock %}

dashboard/templates/slider_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Main Content -->

<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Slider form</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/"><i class="la la-home"></i> IOM</a></li>
                    <li class="breadcrumb-item active">Update form</li>
                </ul>
                <button class="btn btn-icon mobile_menu" type="button"><i class="la la-navicon"></i></button>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn float-right right_icon_toggle_btn" type="button"><i class="la la-arrow-right"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="project-form">

        <div class="card">
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ field.name|title }} {{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <div class="form-group">
                        <p><label for="id_title">Title:</label> <input class="form-control" type="text" name="title" value="{{ form.instance.title }}" maxlength="100" required id="id_title"></p>
                        <p><label for="id_title_nep">Title nep:</label> <input class="form-control" type="text" name="title_nep" value="{{ form.instance.title_nep }}" maxlength="200" id="id_title_nep"></p>
<!--                        <p><label for="id_image">Image:</label> Currently: <a href="{{form.instance.image.url}}">{{form.instance.image.url}}</a>-->
<!--                        <input type="checkbox" name="image-clear" id="image-clear_id">-->
<!--                        <label for="image-clear_id">Clear</label><br>-->
<!--                        Change:-->
<!--<                       <input type="file" name="image" accept="image/*" id="id_image"></p>-->
                    </div>

                    <div class="form_image" style="margin-left:160px">
                        {% if form.instance.image %}
                        <img src="{{form.instance.image.url}}" alt="User"  height="350px" width="350px">
                        {% else %}
                        <img src="/static/dashboard/images/pf.png" alt="User" >
                        {% endif %}

                    </div>
                    <div class="custom-upload form-group">
                        <label class="custom-upload__button" for="id_icon" data-element="custom-upload-button">Choose
                            Icon </label>
                        <input class="custom-upload__input" id="id_icon" name="icon" type="file"
                               data-behaviour="custom-upload-input">

                    </div>

                    <div class="form-footer pull-right">
                        <button type="submit" class="btn" role="button">Save</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock %}